param(
    [string]$Workspace = $env:TS_KB_CONFIG,
    [string]$TaskUser = '',
    [int]$ScanEveryMinutes = 5,
    [string]$InspectionDailyAt = '08:30',
    [string]$EvaluationWeeklyAt = '09:00',
    [int]$WebPort = 8088,
    [switch]$IncludeMaintenance
)

# Install (or refresh) launchers and scheduled tasks on a Windows machine.
# Safe to run repeatedly. Project paths come from this script location; the workspace
# is recorded in a .ts-kb-workspace pointer file so scheduled tasks need no env vars.
$ErrorActionPreference = 'Continue'

$root = Split-Path -Parent $PSScriptRoot
$cli = Join-Path $root '.venv\Scripts\ts-team-kb.exe'
if (-not (Test-Path -LiteralPath $cli)) { Write-Output ('cli missing, create the venv first: ' + $cli); exit 1 }
if (-not $TaskUser) { $TaskUser = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name }

$pointerPath = Join-Path $root '.ts-kb-workspace'
if ($Workspace -and (Test-Path -LiteralPath $Workspace -PathType Leaf)) { $configPath = $Workspace }
elseif ($Workspace) { $configPath = Join-Path $Workspace 'ts-kb.json' }
elseif (Test-Path -LiteralPath $pointerPath) { $configPath = (Get-Content -LiteralPath $pointerPath -Raw).Trim() }
else { $configPath = Join-Path $root 'ts-kb.json' }
if (-not (Test-Path -LiteralPath $configPath)) { Write-Output ('config not found: ' + $configPath); exit 1 }
$work = Split-Path -Parent $configPath
New-Item -ItemType Directory -Force -Path (Join-Path $work 'logs') | Out-Null

# Pointer file: lets the runner scripts find the workspace without env vars.
$pointer = $pointerPath
Set-Content -LiteralPath $pointer -Value $configPath -Encoding Default

# Service launcher (ANSI so non-ASCII paths survive)
$apiCmd = Join-Path $work 'run-api.cmd'
$apiLines = @(
    '@echo off',
    ('set "PYTHONPATH=' + (Join-Path $root 'backend') + '"'),
    ('set "TS_KB_CONFIG=' + $configPath + '"'),
    ('cd /d "' + $work + '"'),
    ('"' + $cli + '" serve --host 0.0.0.0 --port ' + $WebPort + ' >> "' + (Join-Path $work 'logs\api.log') + '" 2>&1')
)
Set-Content -LiteralPath $apiCmd -Value $apiLines -Encoding Default

function New-Launcher {
    param([string]$Name, [string]$Runner)
    $vbs = Join-Path $work $Name
    $lines = @(
        "' hidden launcher, generated by install-windows-tasks.ps1",
        'Set shell = CreateObject("WScript.Shell")',
        ('shell.Environment("Process")("TS_KB_CONFIG") = "' + $configPath + '"'),
        ('shell.CurrentDirectory = "' + $work + '"'),
        ('code = shell.Run "powershell.exe -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ""' + $Runner + '""", 0, True')
        'WScript.Quit code'
    )
    Set-Content -LiteralPath $vbs -Value $lines -Encoding Default
    return $vbs
}

$vbsScheduled = New-Launcher 'run-scheduled-hidden.vbs' (Join-Path $root 'scripts\run-scheduled.ps1')
$vbsInspection = New-Launcher 'run-inspection-hidden.vbs' (Join-Path $root 'scripts\run-inspection.ps1')
$vbsWeb = Join-Path $work 'run-web-service-hidden.vbs'

# Direct-Service-Launcher：直接启动，避免守护脚本在任务上下文里卡死。
$directLines = @(
    "' hidden launcher, generated by install-windows-tasks.ps1",
    'Set shell = CreateObject("WScript.Shell")',
    ('shell.Environment("Process")("TS_KB_CONFIG") = "' + $configPath + '"'),
    ('shell.CurrentDirectory = "' + $work + '"'),
    ('shell.Run "cmd.exe /c " & Chr(34) & "' + (Join-Path $work 'run-api.cmd') + '" & Chr(34), 0, False')
)
Set-Content -LiteralPath $vbsWeb -Value $directLines -Encoding Default

$settings = New-ScheduledTaskSettingsSet -StartWhenAvailable -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
try { $principal = New-ScheduledTaskPrincipal -UserId $TaskUser -LogonType Interactive -RunLevel Limited } catch { Write-Output ($_); exit 1 }

# 作业任务经 VBS 隐藏启动器（shell.Run ..., 0, False，不等待）：
#   · 直连 powershell.exe 在 Interactive 登录类型下会**闪控制台窗口**（每 5 分钟一次），不可接受
#   · 包装器绝不可改成等待模式（..., 0, True）：会挂死并使后续触发全部跳过
#   · 业务成败由 logs/runs.jsonl 的 result 与巡检 run_health 反映，不依赖任务退出码
$a1 = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"' + $vbsScheduled + '"')
$t1 = New-ScheduledTaskTrigger -Once -At (Get-Date).Date -RepetitionInterval (New-TimeSpan -Minutes $ScanEveryMinutes) -RepetitionDuration (New-TimeSpan -Days 3650)
Register-ScheduledTask -TaskName 'TSKnowledgeAgentScheduler' -Action $a1 -Trigger $t1 -Principal $principal -Settings $settings -Force | Out-Null

$a2 = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"' + $vbsInspection + '"')
$t2 = New-ScheduledTaskTrigger -Daily -At $InspectionDailyAt
Register-ScheduledTask -TaskName 'TSKnowledgeAgentInspection' -Action $a2 -Trigger $t2 -Principal $principal -Settings $settings -Force | Out-Null

$vbsEvaluation = $null
if ($IncludeMaintenance) {
    $vbsEvaluation = New-Launcher 'run-evaluation-hidden.vbs' (Join-Path $root 'scripts\run-evaluation.ps1')
    $a4 = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"' + $vbsEvaluation + '"')
    $t4 = New-ScheduledTaskTrigger -Weekly -DaysOfWeek Monday -At $EvaluationWeeklyAt
    Register-ScheduledTask -TaskName 'TSKnowledgeAgentEvaluation' -Action $a4 -Trigger $t4 -Principal $principal -Settings $settings -Force | Out-Null
}

$a3 = New-ScheduledTaskAction -Execute 'wscript.exe' -Argument ('"' + $vbsWeb + '"')
$t3 = New-ScheduledTaskTrigger -AtLogOn -User $TaskUser
Register-ScheduledTask -TaskName 'TSKnowledgeAgentWebService' -Action $a3 -Trigger $t3 -Principal $principal -Settings $settings -Force | Out-Null

$installed = @('TSKnowledgeAgentScheduler')
$installed += 'TSKnowledgeAgentInspection'
if ($IncludeMaintenance) { $installed += 'TSKnowledgeAgentEvaluation' }
$installed += 'TSKnowledgeAgentWebService'
foreach ($n in $installed) {
    $t = Get-ScheduledTask -TaskName $n
    Write-Output ($n + ' state=' + $t.State + ' user=' + $t.Principal.UserId + ' trigger=' + $t.Triggers[0].CimClass.CimClassName + ' swa=' + $t.Settings.StartWhenAvailable)
}
Write-Output ('project=' + $root)
Write-Output ('workspace=' + $work)
Write-Output ('pointer=' + $pointer)
Write-Output ('maintenance_tasks=' + [string]$IncludeMaintenance)
